spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?createDatabaseIfNotExist=true
    username: root
    password: Test@1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
