spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 300000
    max-lifetime: 1800000
    connection-timeout: 30000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    out-of-order: true
    validate-on-migrate: true
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
    org.flywaydb: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR


#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
##    hibernate:
##      ddl-auto: update
#    flyway:
#      enabled: true
#      baseline-on-migrate: true
#      locations: classpath:db/migration
#      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
#      username: ${MYSQL_USER}
#      password: ${MYSQL_PASSWORD}
#      driver-class-name: com.mysql.cj.jdbc.Driver