spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    hibernate:
#      ddl-auto: none
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true