spring:
  application.name: portal
  profiles:
    active: dev
  jwt:
    secret: ${JWT_SECRET:cmUex7qBycCU+I2o7eETb38yTarR9IUACbl087CExfPouf6+R4HKm7Gda58/70Y2uzlKHvPKAOutzmm5y8IFqw==}
    token:
      key: ${TOKEN_KEY:43c7a0b35759172db9cf420e9a0e19ad}
      accessTokenExpiration: 9000
markets-tack:
  api:
    key: ${TOKEN_KEY}


#spring:
#  application.name: portal
#  profiles:
#    active: dev
#  jwt:
#    secret: ${JWT_SECRET}
#    accessTokenExpiration: 9000
#markets-tack:
#  api:
#    key: ${TOKEN_KEY}
