spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true}
      username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER}}
      password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD}}
      driver-class-name: com.mysql.cj.jdbc.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
##    hibernate:
##      ddl-auto: update
#    flyway:
#      enabled: true
#      baseline-on-migrate: true
#      locations: classpath:db/migration
#      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
#      username: ${MYSQL_USER}
#      password: ${MYSQL_PASSWORD}
#      driver-class-name: com.mysql.cj.jdbc.Driver